### ISSUE TITLE
Fancy imagebar slows down webtrees

### ISSUE THREAD

**Issue by HonkXL** [JustCarmen/webtrees-fancy-imagebar#64] opened 2021-03-12 08:18 UTC
In webtrees 1.7.x using fancy imagebar was no problem.
Since upgrading to webtrees 2.0.12, my webtrees is dramatically slow when fancy imagebar is in use. When I deactivate it, everything works fast.

**Comment by JustCarmen** [comment] 2021-03-20 15:50
Duplicate of https://github.com/JustCarmen/webtrees-fancy-imagebar/issues/60

**Closed by JustCarmen** 2021-03-20 15:50 UTC
