### ISSUE TITLE
I get error on my test site pages. They are removed when  I refresh the page.

### ISSUE THREAD

**Issue by melizaa** [JustCarmen/webtrees-fancy-imagebar#78] opened 2021-08-20 11:30 UTC
imagecopyresampled() expects parameter 2 to be resource, bool given …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:524
#0 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(524): imagecopyresampled()
#1 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(338): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyThumb()
#2 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(213): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyImagebar()
#3 …/resources/views/layouts/default.phtml(184): JustCarmen\Webtrees\Module\FancyImagebarModule->bodyContent()
#4 [internal function]: Fisharebest\Webtrees\View::{closure}()
#5 …/vendor/illuminate/collections/Collection.php(642): array_map()
#6 …/resources/views/layouts/default.phtml(185): Illuminate\Support\Collection->map()
#7 …/app/View.php(189): include('/home/amitys/fu...')
#8 …/app/View.php(286): Fisharebest\Webtrees\View->render()
#9 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make()
#10 …/app/Http/ViewResponseTrait.php(54): view()
#11 …/app/Http/RequestHandlers/EditFactPage.php(110): Fisharebest\Webtrees\Http\RequestHandlers\EditFactPage->viewResponse()
#12 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\EditFactPage->handle()
#13 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#14 …/app/Module/HitCountFooterModule.php(157): Middleland\Dispatcher->handle()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#16 …/app/Http/Middleware/AuthEditor.php(57): Middleland\Dispatcher->handle()
#17 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthEditor->process()
#18 …/app/Http/Middleware/CheckCsrf.php(75): Middleland\Dispatcher->handle()
#19 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#21 …/app/Webtrees.php(241): Middleland\Dispatcher->dispatch()
#22 …/app/Http/Middleware/Router.php(149): Fisharebest\Webtrees\Webtrees::dispatch()
#23 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#24 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#25 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#26 …/app/Http/Middleware/LoadRoutes.php(74): Middleland\Dispatcher->handle()
#27 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#28 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#29 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#30 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#31 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#32 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#33 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#34 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#35 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#36 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#37 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#38 …/app/Http/Middleware/UseLanguage.php(69): Middleland\Dispatcher->handle()
#39 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#40 …/app/Http/Middleware/UseSession.php(75): Middleland\Dispatcher->handle()
#41 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#42 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#43 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#44 …/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle()
#45 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process()
#46 …/app/Http/Middleware/UseDatabase.php(132): Middleland\Dispatcher->handle()
#47 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#48 …/app/Http/Middleware/BadBotBlocker.php(223): Middleland\Dispatcher->handle()
#49 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#50 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#51 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#52 …/app/Http/Middleware/ContentLength.php(52): Middleland\Dispatcher->handle()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#54 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#55 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#56 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#57 …/app/Http/Middleware/HandleExceptions.php(89): Middleland\Dispatcher->handle()
#58 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#59 …/app/Http/Middleware/BaseUrl.php(77): Middleland\Dispatcher->handle()
#60 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#61 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#62 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#63 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#65 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#66 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#67 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#68 …/app/Webtrees.php(241): Middleland\Dispatcher->dispatch()
#69 …/app/Webtrees.php(228): Fisharebest\Webtrees\Webtrees::dispatch()
#70 …/index.php(44): Fisharebest\Webtrees\Webtrees->httpRequest()
#71 {main}

**Comment by JustCarmen** [comment] 2021-09-06 07:12
Duplicate of #75

**Closed by JustCarmen** 2021-09-06 07:12 UTC
