### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by anjop** [JustCarmen/webtrees-fancy-imagebar#44] opened 2020-09-28 12:52 UTC
Very often I get following very long error report on my website using the imagebar:
What could be the problem please?

![Bildschirmfoto 2020-09-28 um 14 49 00](https://user-images.githubusercontent.com/25871555/94434391-02e3b180-019a-11eb-90de-4eaa0982e43b.png)

**Comment by JustCarmen** [comment] 2020-09-28 21:31
This is a duplicate of #42

**Closed by JustCarmen** 2020-09-28 21:31 UTC
