### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by webtrees-pesz** [JustCarmen/webtrees-fancy-imagebar#90] opened 2021-10-25 16:18 UTC
What is the reason for such a sporadic error message?

<b>imagejpeg() expects parameter 1 to be resource, null given …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:376</b> <b>#0 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(376): imagejpeg(NULL, &#039;/var/www/web838...&#039;)</b> <b>#1 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(232): JustCarmen\Webtrees\Module\FancyImagebarModule-&gt;fancyImagebar()</b> <b>#2 …/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(205): JustCarmen\Webtrees\Module\FancyImagebarModule-&gt;bodyContent()</b> #3 [internal function]: Fisharebest\Webtrees\View::{closure}(Object(JustCarmen\Webtrees\Module\FancyImagebarModule), &#039;_jc-fancy-image...&#039;) #4 …/vendor/illuminate/support/Collection.php(1120): array_map(Object(Closure), Array, Array) <b>#5 …/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(206): Illuminate\Support\Collection-&gt;map(Object(Closure))</b> #6 …/app/View.php(189): include(&#039;/var/www/web838...&#039;) #7 …/app/View.php(286): Fisharebest\Webtrees\View-&gt;render() #8 …/app/Helpers/functions.php(203): Fisharebest\Webtrees\View::make(&#039;layouts/default&#039;, Array) #9 …/app/Http/ViewResponseTrait.php(55): view(&#039;layouts/default&#039;, Array) #10 …/app/Http/RequestHandlers/IndividualPage.php(151): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage-&gt;viewResponse(&#039;individual-page&#039;, Array) #11

**Comment by webtrees-pesz** [comment] 2021-11-09 11:12
Any idea?

**Comment by JustCarmen** [comment] 2021-11-28 06:54
This is a duplicate of #89.

It is fixed in the development version. It will be added to the next release.

**Closed by JustCarmen** 2021-11-28 06:54 UTC
