### ISSUE TITLE
Error - Division by zero

### ISSUE THREAD

**Issue by melizaa** [JustCarmen/webtrees-fancy-imagebar#50] opened 2020-10-15 06:15 UTC
In my test system I show very few media objects to site visitors.
When I am not signed-in I see

Division by zero …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php:487
#0 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(487): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'Division by zer...', '/home/amitys/fu...', 487, Array)
#1 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(336): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyThumb('../webtrees-dat...', '80', '0')
#2 …/modules_v4/jc-fancy-imagebar/FancyImagebarModule.php(215): JustCarmen\Webtrees\Module\FancyImagebarModule->fancyImagebar()
etc.

<https://www.amitys.com/future/index.php?route=%2Ffuture%2Ftree%2FGedcomFuture.ged>

**Comment by melizaa** [comment] 2020-10-16 08:14
I have 8 gif files that I see on the test system's wt individual page, in the media list and in the control panel - manage media.

How can I adjust the code and print in testing the file name of the media record that causes $source_height to be zero?

**Comment by melizaa** [comment] 2020-10-16 09:42
I changed the media type that I show to Photo and I made sure that none of the .gif files of the GEDCOM file that I look at are defined as Photo.

The GEDCOM is configured with "Show the family tree" and "Show private relationships" as Show to visitors. All the rest is defined as Show to members or Show to managers.

Two individuals are defined as "Show to visitors" on their individual page.

I see still the error when I am not signed-in.

**Comment by JustCarmen** [comment] 2020-10-18 06:58
Does this helps? https://github.com/JustCarmen/webtrees-fancy-imagebar/commit/a3d48d551190a93e9a06547476916d7ca557c1c6

**Comment by melizaa** [comment] 2020-10-18 13:57
It does not help.

I updated the configuration and changed the Media Folder from media to media/pictures and since then I do not see the error.

**Comment by JustCarmen** [comment] 2020-11-28 20:56
Since you haven't seen the error recently (as far as I know) and I still can not reproduce it I will close this issue. You may reopen it whenever you reencounter the problem.

**Closed by JustCarmen** 2020-11-28 20:56 UTC

**Comment by melizaa** [comment] 2020-11-29 10:31
I continue to see the error every now and again when I am signed-in to my future and test test systems.
I have edited a lot of media files and I do not see the error often.
It would be great, if we would get an error message that would tell us which media object causes the problem.
