### ISSUE TITLE
.jc-fancy-imagebar-map: Firefox inspector shows "overflow"

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-fancy-imagebar#84] opened 2021-09-20 08:20 UTC
fc-imagebar creates more than 700 'area shape' entries. Up to:

`<area shape="rect" coords="100887, 0, 100947, 80" alt="Elisabeth Beppie Honig (1897–1984)" title="Elisabeth Beppie Honig (1897–1984)" href="https://wijzijnfamilie.nl/tree/wijzijnfamilie/individual/I3287/Elisabeth-Beppie-Honig" data-coords="100887, 0, 100947, 80">
`

Is this a problem? I guess even a 4k monitor doesn't need that many images?! 

![grafik](https://user-images.githubusercontent.com/28572767/133973595-80f60823-487f-4d83-88d2-e7d9ebd210cf.png)

**Comment by JustCarmen** [comment] 2021-09-23 08:55
700 images is way to much. I wasn't able to reproduce this.

But I think I have improved the performance by using another calculation method to determine the amount of images needed to fill up the entire imagebar.

The width of each thumbnail is calculated and processing stops as soon as the total width reaches the width of the imagebar.
If there are less images to fill up the entire imagebar the average width of the processed images is used to determine the number of extra images. This gives a more accurate result without wasting resources.

Hope this helps.

**Comment by JustCarmen** [comment] 2021-09-24 08:54
See my last comment at #69. Since this issue is related I think this issue is also solved with the latest commits.

I will close this issue now. If you still have troubles please open a new issue.

**Closed by JustCarmen** 2021-09-24 08:54 UTC

**Comment by ungeahnt** [comment] 2021-09-24 17:25
First: Thanks a lot for V2.1.2. It brings a real performance boost!

But I see this "overflow" also with V2.1.2 (Firefox web-dev-tools) but it's not a problem for me (I hope so ;) ). 
So I won't open a new issue.

Only for completness:
> 700 images is way to much. I wasn't able to reproduce this.
I must have misinterpreted the Firefox information. Probably no 700 thumbs are generated, but it is about the links (maps/coords?) between INDI and thumbs?

With the update to V2.1.2 fc-imagebar  creates on my website (proavitus.de) 331 items of "area shape" with coords from 
`area shape="rect" coords="158, 0, 217, 80` to
`area shape="rect" coords="59195, 0, 59256, 80`
and Firefox shows an "overflow" (equal to the image above). 

Maybe this is intentional, that the coords go to 59256, but I'm just wondering, since the jpeg-file that is created on my site is only of the size of 3840x80 pixels (dual-monitor) and includes only 61 (and a half) thumbs. 

As mentioned above, I have no problem with that. I just noticed it and thought it might be a performance problem.
